### ISSUE TITLE
Authentication against Active directory stopped working

### ISSUE THREAD

**Issue by xmatthias** [jupyterhub/ldapauthenticator#79] opened 2018-06-12 14:16 UTC
Since commit c881a9fba7e73ba938adc744e7e0deed8a262b15 the working authentication against Active directory does not work anymore.

from the logs:
### after c881a9fba7e73ba938adc744e7e0deed8a262b15 
```
[D 2018-06-12 14:01:04.368 JupyterHub ldapauthenticator:299] TYPE= 'True'
[D 2018-06-12 14:01:04.369 JupyterHub ldapauthenticator:223] Looking up user with search_base=DC=example,dc=com, search_filter='(sAMAccountName=x.matthias)', attributes=sAMAccountName
[D 2018-06-12 14:01:04.587 JupyterHub ldapauthenticator:278] Attempting to bind x.matthias with CN=X Matthias\,OU=Users\,DC=example\,DC=com
[D 2018-06-12 14:01:04.589 JupyterHub ldapauthenticator:330] Status of user bind x.matthias with CN=X Matthias\,OU=Users\,DC=example\,DC=com : False
    LDAPBindError: automatic bind not successful - invalidCredentials
```

### before 
```
[D 2018-06-12 14:09:53.714 JupyterHub ldapauthenticator:299] TYPE= 'True'
[D 2018-06-12 14:09:53.715 JupyterHub ldapauthenticator:223] Looking up user with search_base=DC=example,dc=com, search_filter='(sAMAccountName=x.matthias)', attributes=sAMAccountName
[D 2018-06-12 14:09:53.943 JupyterHub ldapauthenticator:278] Attempting to bind x.matthias with CN=X Matthias,OU=Users,DC=example,DC=com
[D 2018-06-12 14:09:54.709 JupyterHub ldapauthenticator:328] Status of user bind x.matthias with CN=X Matthias,OU=Users,DC=example,DC=com : True
[D 2018-06-12 14:09:54.709 JupyterHub ldapauthenticator:334] username:x.matthias Using dn CN=X Matthias,OU=Users,DC=example,DC=com
[D 2018-06-12 14:09:54.716 JupyterHub base:268] Setting cookie for x.matthias: jupyter-hub-token, {'httponly': True}
```

The problem seems to be the escaped `,` - which does not work against Windows AD controllers, and currently cannot be disabled (at least not that i'd have found it).

related config: 
``` python
c.JupyterHub.authenticator_class = 'ldapauthenticator.LDAPAuthenticator'
c.LDAPAuthenticator.user_attribute = 'sAMAccountName'

c.LDAPAuthenticator.server_address = 'ldap://domaincontroller.example.com'
c.LDAPAuthenticator.server_port = 3268
c.LDAPAuthenticator.lookup_dn = True
c.LDAPAuthenticator.lookup_dn_search_filter = '({login_attr}={login})'
c.LDAPAuthenticator.lookup_dn_search_user = 'CN=HelperUser,OU=Service Accounts,OU=Rights and Policies,OU=GA,DC=example,DC=com'
c.LDAPAuthenticator.lookup_dn_search_password = '<password>'
c.LDAPAuthenticator.base_dn = 'dc=example,dc=com'
c.LDAPAuthenticator.bind_dn_template = [
        '{username}',
]
c.LDAPAuthenticator.user_search_base = 'dc=example,dc=com'
c.LDAPAuthenticator.user_attribute = 'sAMAccountName'
c.LDAPAuthenticator.lookup_dn_user_dn_attribute = 'DistinguishedName'
c.LDAPAuthenticator.escape_userdn = False
c.LDAPAuthenticator.allowed_groups = [
    'CN=JHub-Admin,OU=Groups,OU=Rights and Policies,OU=GA,DC=example,DC=com'
]

```
unfortunately, changing `escape_userdn` did not have any effect, as it's in an area where this is not checked.
https://github.com/jupyterhub/ldapauthenticator/blob/45ee38febb908168059142f799ace4357b33d34a/ldapauthenticator/ldapauthenticator.py#L305

All attributes have been changed to "example.com" ...

**Comment by dhirschfeld** [comment] 2018-06-13 04:31
Thanks for the report @xmatthias. The problem isn't to do with Windows AD controllers (I'm running on Windows) but instead is the use of `DN` for the `lookup_dn_user_dn_attribute`.

The code as is assumes `c.LDAPAuthenticator.lookup_dn_user_dn_attribute = 'CN'` so that's definitely something to fix.

In the interim,  can you confirm if using the below config fixes the problem?
```
c.LDAPAuthenticator.lookup_dn_user_dn_attribute = 'CN'
c.LDAPAuthenticator.bind_dn_template = "CN={username},OU=Users,DC=example,DC=com"
c.LDAPAuthenticator.user_search_base = "OU=Users,DC=example,DC=com"
```

**Comment by dhirschfeld** [comment] 2018-06-13 04:31
Also, you should delete the below:
```
c.LDAPAuthenticator.base_dn = 'dc=example,dc=com'
```

`base_dn` doesn't appear to be a valid config?

**Comment by xmatthias** [comment] 2018-06-13 06:39
Thanks for the quick response.

Your approach does work - but is unsuitable in my environment as we have multi-forest environment (our users come from 3 separate forests). This would not be a problem per se, however, the forests themselvs are nested into OU's (one nested OU per region / site - without real standard) - so i would need to use an array of several 100 bind-templates to actually have it work, which is error-prone and very cumbersome to maintain.

My template would need to look something like `"CN={username},OU=Users,*,DC=example,DC=com"` - but wildcards in this position are not supported by ldap as far as i know.


I came a bit further inspired by your suggestions - using UPN i could get login to work "somehow"- however this breaks "allowed_groups" - as "x.matthias@example.com" is not member nor uniqueMember, but the CN would be.

```
c.LDAPAuthenticator.lookup_dn_user_dn_attribute = 'UserPrincipalName'
```

**Comment by dhirschfeld** [comment] 2018-06-13 07:04
Yes, the bug should be fixed. I thought that might give you a workaround in the interim but it sounds like that won't work.

**Comment by xmatthias** [comment] 2018-06-13 07:51
it's not a blocking issue for me at the moment - i can pip install the "old" commit directly in the meantime - so i found a temporary workaround (even though one I'd like to get rid of ASAP)

**Closed** 2018-06-14 11:36 UTC
Labels: configuration, ¡bug!

**Comment by dhirschfeld** [comment] 2018-06-14 11:50
Version 1.2.2 has been published to pypi - please let me know if this fixes the problem for you!

**Comment by xmatthias** [comment] 2018-06-14 12:51
Wow, that was quick

thanks a lot - works for me 👍

**Comment by mannevijayakrishna** [comment] 2019-01-28 19:32
can some one please help with the same kind of issue #115
