### ISSUE TITLE
500 : Internal Server Error 

### ISSUE THREAD

**Issue by yisampi** [jupyterhub/ldapauthenticator#99] opened 2018-08-09 07:29 UTC
config jupyterhub with ldapauthenticator:
c.JupyterHub.authenticator_class = 'ldapauthenticator.LDAPAuthenticator'
c.LDAPAuthenticator.server_address = 'whcc.cn'
c.LDAPAuthenticator.server_port = 2389
c.LDAPAuthenticator.allowed_groups = ["CN=whcc IT Development-3,OU=WHCCMail_Groups,OU=WHHC_Groups,DC=whcc,DC=cn",]
c.LDAPAuthenticator.lookup_dn = True
c.LDAPAuthenticator.user_search_base = 'OU=WHHC_Users,dc=whcc,dc=cn'

log from jupterhub:
[E 2018-08-09 15:20:09.540 JupyterHub log:158] 500 POST /hub/login?next= (@::ffff:ip) 112.39ms
[E 2018-08-09 15:20:09.656 JupyterHub web:1621] Uncaught exception POST /hub/login?next= (::ffff:ip)
    HTTPServerRequest(protocol='http', host='ip:9997', method='POST', uri='/hub/login?next=', version='HTTP/1.1', remote_ip='::ffff:ip')
    Traceback (most recent call last):
      File "/opt/anaconda2/envs/py36/lib/python3.6/site-packages/tornado/web.py", line 1543, in _execute
        result = yield result
      File "/opt/anaconda2/envs/py36/lib/python3.6/site-packages/jupyterhub/handlers/login.py", line 81, in post
        user = await self.login_user(data)
      File "/opt/anaconda2/envs/py36/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 472, in login_user
        authenticated = await self.authenticate(data)
      File "/opt/anaconda2/envs/py36/lib/python3.6/site-packages/jupyterhub/auth.py", line 257, in get_authenticated_user
        authenticated = await maybe_future(self.authenticate(handler, data))
      File "/opt/anaconda2/envs/py36/lib/python3.6/types.py", line 248, in wrapped
        coro = func(*args, **kwargs)
      File "/opt/anaconda2/envs/py36/lib/python3.6/site-packages/ldapauthenticator/ldapauthenticator.py", line 301, in authenticate
        resolved_username = self.resolve_username(username)
      File "/opt/anaconda2/envs/py36/lib/python3.6/site-packages/ldapauthenticator/ldapauthenticator.py", line 237, in resolve_username
        attributes=[self.lookup_dn_user_dn_attribute]
      File "/opt/anaconda2/envs/py36/lib/python3.6/site-packages/ldap3/core/connection.py", line 779, in search
        check_names=self.check_names)
      File "/opt/anaconda2/envs/py36/lib/python3.6/site-packages/ldap3/operation/search.py", line 376, in search_operation
        request['attributes'] = build_attribute_selection(attributes, schema)
      File "/opt/anaconda2/envs/py36/lib/python3.6/site-packages/ldap3/operation/search.py", line 311, in build_attribute_selection
        attribute_selection[index] = Selector(attribute)
      File "/opt/anaconda2/envs/py36/lib/python3.6/site-packages/pyasn1/type/univ.py", line 819, in __init__
        base.AbstractSimpleAsn1Item.__init__(self, value, **kwargs)
      File "/opt/anaconda2/envs/py36/lib/python3.6/site-packages/pyasn1/type/base.py", line 240, in __init__
        value = self.prettyIn(value)
      File "/opt/anaconda2/envs/py36/lib/python3.6/site-packages/pyasn1/type/univ.py", line 878, in prettyIn
        return bytes(value)
    TypeError: cannot convert 'NoneType' object to bytes
    
[E 2018-08-09 15:20:09.657 JupyterHub log:150] {
      "X-Forwarded-Host": "ip:9997",
      "X-Forwarded-Proto": "http",
      "X-Forwarded-Port": "9997",
      "X-Forwarded-For": "::ffff:ip",
      "Cookie": "_xsrf=2|ed5fd728|74263f7cc593ade9e0e24903448b6e57|1533181774; jupyterhub-session-id=1ae4d011ab104033a838c85e6c1c9af8; oauthenticator-state=\"2|1:0|10:1533790104|20:oauthenticator-state|120:ZXlKemRHRjBaVjlwWkNJNklDSTFObU15WW1RM01qazJaVGMwWlRKa1lUTmlNakExTldaall6RXpORFJrTVNJc0lDSnVaWGgwWDNWeWJDSTZJQ0lpZlE9PQ==|cba590f7e071100f419312941f595de78b57c33244dd56f3490f968b1e12bdd3\"",
      "Cache-Control": "no-cache",
      "Connection": "close",
      "Dnt": "1",
      "Content-Length": "35",
      "Host": "ip:9997",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/x-www-form-urlencoded",
      "User-Agent": "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko",
      "Accept-Language": "zh-CN",
      "Referer": "http://ip:9997/hub/login?next=",
      "Accept": "text/html, application/xhtml+xml, */*"
    }
[E 2018-08-09 15:20:09.657 JupyterHub log:158] 500 POST /hub/login?next= (@::ffff:ip) 94.03ms

**Comment by dhirschfeld** [comment] 2018-08-09 10:46
Have you provided `lookup_dn_user_dn_attribute` or `bind_dn_template ` or other required attributes as specified in the readme?

**Comment by yisampi** [comment] 2018-08-10 01:17
@dhirschfeld thanks for your help.
 And i have changed the configuration of jupyterhub like:
c.JupyterHub.authenticator_class = 'ldapauthenticator.LDAPAuthenticator'
c.LDAPAuthenticator.server_address = 'whcc.cn'
c.LDAPAuthenticator.server_port = 2389
c.LDAPAuthenticator.bind_dn_template = 'CN={username},OU=WHCC_Users,dc=whcc,dc=cn'
c.LDAPAuthenticator.allowed_groups = ["CN=HCC IT Development-3,OU=Mail_Groups,OU=WHCC_Groups,DC=whcc,DC=cn",]
c.LDAPAuthenticator.lookup_dn = True
c.LDAPAuthenticator.user_search_base = 'OU=WHCC_Users,dc=whcc,dc=cn'
c.LDAPAuthenticator.lookup_dn_search_filter = '({login_attr}={login})'
c.LDAPAuthenticator.lookup_dn_search_user = '*********'
c.LDAPAuthenticator.lookup_dn_search_password = '*******'
c.LDAPAuthenticator.lookup_dn_user_dn_attribute = 'CN'
c.LDAPAuthenticator.user_attribute = 'sAMAccountName'
c.LDAPAuthenticator.use_ssl = False
c.LDAPAuthenticator.escape_userdn = False

when i login with ldap account, the error logs are:

[I 2018-08-10 09:11:01.715 JupyterHub log:158] 200 GET /hub/login (@::ffff:10.64.44.34) 25.33ms
[W 2018-08-10 09:11:07.096 JupyterHub ldapauthenticator:379] Invalid password for user sam.yi
[W 2018-08-10 09:11:07.096 JupyterHub base:504] Failed login for sam.yi
[I 2018-08-10 09:11:07.097 JupyterHub log:158] 200 POST /hub/login?next= (@::ffff:10.64.44.34) 695.47ms

jupyterhub --version
0.9.1
jupyterhub-ldapauthenticator 1.2.2

**Comment by yisampi** [comment] 2018-08-10 01:32
open debug mode for jupyterhub, more logs are:
[D 2018-08-10 09:30:03.309 JupyterHub ldapauthenticator:299] TYPE= 'True'
[D 2018-08-10 09:30:03.310 JupyterHub ldapauthenticator:223] Looking up user with search_base=OU=WHCC_Users,dc=whcc,dc=cn, search_filter='(sAMAccountName=sam.yi)', attributes=sAMAccountName
[D 2018-08-10 09:30:03.712 JupyterHub ldapauthenticator:278] Attempting to bind sam.yi with CN=Sam Yi,OU=WHCC_Users,dc=whcc,dc=cn
[D 2018-08-10 09:30:03.770 JupyterHub ldapauthenticator:333] Status of user bind sam.yi with CN=Sam Yi,OU=WHCC_Users,dc=whcc,dc=cn : False
    LDAPBindError: automatic bind not successful - invalidCredentials
[W 2018-08-10 09:30:03.770 JupyterHub ldapauthenticator:379] Invalid password for user sam.yi
[W 2018-08-10 09:30:03.771 JupyterHub base:504] Failed login for sam.yi
[I 2018-08-10 09:30:03.794 JupyterHub log:158] 200 POST /hub/login?next= (@::ffff:********) 487.11ms

**Comment by dhirschfeld** [comment] 2018-08-10 01:59
If you remove the `allowed_groups` configuration does it work? 

Does your `DN` as given in the logs look correct? On windows I can check my `DN` with
```
dsquery user -samid dhirschfeld
```

**Comment by yisampi** [comment] 2018-08-10 05:50
i modify the configuration and i think i got the auth from LDAP. but there is another error from jupyterhub:
c.JupyterHub.authenticator_class = 'ldapauthenticator.LDAPAuthenticator'
c.LDAPAuthenticator.server_address = 'whcc.cn'
c.LDAPAuthenticator.server_port = 389
c.LDAPAuthenticator.bind_dn_template = []
c.LDAPAuthenticator.lookup_dn = True
c.LDAPAuthenticator.user_search_base = 'OU=WHCC_Users,dc=whcc,dc=cn'
c.LDAPAuthenticator.lookup_dn_search_filter = '({login_attr}={login})'
c.LDAPAuthenticator.lookup_dn_search_user = '********'
c.LDAPAuthenticator.lookup_dn_search_password = '*******'
#c.LDAPAuthenticator.lookup_dn_user_dn_attribute = 'CN'
c.LDAPAuthenticator.user_attribute = 'sAMAccountName'
c.LDAPAuthenticator.use_ssl = False


error logs are:
[D 2018-08-10 13:40:19.904 JupyterHub log:158] 304 GET /hub/login (@::ffff:8888888888) 1.59ms
[D 2018-08-10 13:40:23.533 JupyterHub ldapauthenticator:299] TYPE= 'True'
[D 2018-08-10 13:40:23.533 JupyterHub ldapauthenticator:223] Looking up user with search_base=OU=WHCC_Users,dc=whcc,dc=cn, search_filter='(sAMAccountName=sam.yi)', attributes=sAMAccountName
[E 2018-08-10 13:40:23.774 JupyterHub web:1621] Uncaught exception POST /hub/login?next= (::ffff:8888888888)
    HTTPServerRequest(protocol='http', host='9,9.9.9:9997', method='POST', uri='/hub/login?next=', version='HTTP/1.1', remote_ip='::ffff:8888888888')
    Traceback (most recent call last):
      File "/opt/anaconda2/envs/py36/lib/python3.6/site-packages/tornado/web.py", line 1543, in _execute
        result = yield result
      File "/opt/anaconda2/envs/py36/lib/python3.6/site-packages/jupyterhub/handlers/login.py", line 81, in post
        user = await self.login_user(data)
      File "/opt/anaconda2/envs/py36/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 473, in login_user
        authenticated = await self.authenticate(data)
      File "/opt/anaconda2/envs/py36/lib/python3.6/site-packages/jupyterhub/auth.py", line 257, in get_authenticated_user
        authenticated = await maybe_future(self.authenticate(handler, data))
      File "/opt/anaconda2/envs/py36/lib/python3.6/types.py", line 248, in wrapped
        coro = func(*args, **kwargs)
      File "/opt/anaconda2/envs/py36/lib/python3.6/site-packages/ldapauthenticator/ldapauthenticator.py", line 301, in authenticate
        resolved_username = self.resolve_username(username)
      File "/opt/anaconda2/envs/py36/lib/python3.6/site-packages/ldapauthenticator/ldapauthenticator.py", line 237, in resolve_username
        attributes=[self.lookup_dn_user_dn_attribute]
      File "/opt/anaconda2/envs/py36/lib/python3.6/site-packages/ldap3/core/connection.py", line 760, in search
        if ';' in attribute_name:  # remove tags
    TypeError: argument of type 'NoneType' is not iterable
    
[D 2018-08-10 13:40:23.774 JupyterHub base:845] No template for 500
[E 2018-08-10 13:40:23.775 JupyterHub log:150] {
      "X-Forwarded-Host": "9,9.9.9:9997",
      "X-Forwarded-Proto": "http",
      "X-Forwarded-Port": "9997",
      "X-Forwarded-For": "::ffff:8888888888",
      "Cookie": "_xsrf=2|ed5fd728|74263f7cc593ade9e0e24903448b6e57|1533181774; jupyterhub-session-id=8c1d4ab6aa874f7f87b2d03d1a9b9b53",
      "Cache-Control": "no-cache",
      "Connection": "close",
      "Dnt": "1",
      "Content-Length": "35",
      "Host": "10.29.31.70:9997",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/x-www-form-urlencoded",
      "User-Agent": "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko",
      "Accept-Language": "zh-CN",
      "Referer": "http://9,9.9.9:9997/hub/login",
      "Accept": "text/html, application/xhtml+xml, */*"
    }
[E 2018-08-10 13:40:23.775 JupyterHub log:158] 500 POST /hub/login?next= (@::ffff:8888888888) 243.52ms

**Comment by dhirschfeld** [comment] 2018-08-10 05:58
`lookup_dn_user_dn_attribute` is commented out there

**Comment by yisampi** [comment] 2018-08-10 06:03
uncomment the lookup_dn_user_dn_attribute = 'CN', then the error logs are:
[D 2018-08-10 14:02:01.738 JupyterHub ldapauthenticator:299] TYPE= 'True'
[D 2018-08-10 14:02:01.739 JupyterHub ldapauthenticator:223] Looking up user with search_base=OU=WHCC_Users,dc=whcc,dc=cn, search_filter='(sAMAccountName=sam.yi)', attributes=sAMAccountName
[W 2018-08-10 14:02:02.095 JupyterHub ldapauthenticator:379] Invalid password for user sam.yi
[W 2018-08-10 14:02:02.095 JupyterHub base:504] Failed login for sam.yi
[I 2018-08-10 14:02:02.119 JupyterHub log:158] 200 POST /hub/login?next= (@::ffff:10.64.44.34) 382.19ms
[D 2018-08-10 14:02:04.137 JupyterHub ldapauthenticator:299] TYPE= 'True'
[D 2018-08-10 14:02:04.137 JupyterHub ldapauthenticator:223] Looking up user with search_base=OU=HC_Users,dc=hc,dc=cn, search_filter='(sAMAccountName=sam.yi)', attributes=sAMAccountName
[W 2018-08-10 14:02:04.618 JupyterHub ldapauthenticator:379] Invalid password for user sam.yi
[W 2018-08-10 14:02:04.619 JupyterHub base:504] Failed login for sam.yi
[I 2018-08-10 14:02:04.620 JupyterHub log:158] 200 POST /hub/login?next= (@::ffff:10.64.44.34) 483.93ms

**Comment by dhirschfeld** [comment] 2018-08-10 06:09
Your `bind_dn_template` seems to be empty again.

**Comment by dhirschfeld** [comment] 2018-08-10 06:12
I don't know that I can help you further. I recommend you step through the code in a debugger such as PyCharm to try and understand what is going wrong.

A good debugging technique is to find out what *does* work for you using the underlying [`ldap3`](https://ldap3.readthedocs.io/) library and then finding out what is `ldapauthenticator` is doing differently

**Comment by yisampi** [comment] 2018-08-10 06:53
below configuratin works for me but i have to create the ldap account in linux system also.
c.JupyterHub.authenticator_class = 'ldapauthenticator.LDAPAuthenticator'
c.LDAPAuthenticator.server_address = 'whcc.cn'
c.LDAPAuthenticator.server_port = 389
c.LDAPAuthenticator.bind_dn_template = []
c.LDAPAuthenticator.bind_dn_template = ['CN={username},OU=VIP,OU=WHCC_Location,OU=WHCC_Users,DC=hc,DC=cn','CN={username},OU=**,OU=****,OU=WHCC_Location,OU=WHCC_Users,dc=hc,dc=cn']
c.LDAPAuthenticator.lookup_dn = True
c.LDAPAuthenticator.user_search_base = 'OU=WHCC_Users,dc=whcc,dc=cn'
c.LDAPAuthenticator.lookup_dn_search_filter = '({login_attr}={login})'
c.LDAPAuthenticator.lookup_dn_search_user = '**********'
c.LDAPAuthenticator.lookup_dn_search_password = '***********'
c.LDAPAuthenticator.lookup_dn_user_dn_attribute = 'CN'
c.LDAPAuthenticator.user_attribute = 'sAMAccountName'
c.LDAPAuthenticator.use_ssl = False
c.LDAPAuthenticator.escape_userdn = False

@dhirschfeld thanks very much.

**Comment by dhirschfeld** [comment] 2018-08-10 10:27
I'm glad you managed to get it resolved! Since you managed to get it working I'll go ahead and close this but if you're still having problems feel free to re-open and hopefully someone with more linux knowledge can help out...

**Closed by dhirschfeld** 2018-08-10 10:27 UTC

**Comment by sigurdurb** [comment] 2018-08-20 09:03
@yisampi Can you expand on how you created "the ldap account in the linux system also" ??

**Comment by tedstrauss** [comment] 2018-08-22 20:11
I have the same problem, and have tried hundreds of combinations of the LDAP settings, always get the same error. 

```
[I 2018-08-22 16:06:19.309 JupyterHub app:1581] JupyterHub is now running at https://my.jupyterhub.edu:443/
[D 2018-08-22 16:06:59.141 JupyterHub ldapauthenticator:299] TYPE= 'True'
[D 2018-08-22 16:06:59.143 JupyterHub ldapauthenticator:223] Looking up user with search_base=OU=Faculty,DC=campus,DC=niceschool,DC=edu, search_filter='(sAMAccountName=tstrau)', attributes=sAMAccountName
[E 2018-08-22 16:07:09.147 JupyterHub web:1621] Uncaught exception POST /hub/login?next= (132.206.178.43)
    HTTPServerRequest(protocol='https', host='my.jupyterhub.edu', method='POST', uri='/hub/login?next=', version='HTTP/1.1', remote_ip='132.206.178.43')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/tornado/web.py", line 1543, in _execute
        result = yield result
      File "/usr/lib/python3.4/asyncio/futures.py", line 275, in result
        raise self._exception
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/handlers/login.py", line 83, in post
        user = yield self.login_user(data)
      File "/usr/lib/python3.4/asyncio/futures.py", line 275, in result
        raise self._exception
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/handlers/base.py", line 328, in login_user
        authenticated = yield self.authenticate(data)
      File "/usr/lib/python3.4/asyncio/futures.py", line 275, in result
        raise self._exception
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/auth.py", line 227, in get_authenticated_user
        authenticated = yield self.authenticate(handler, data)
      File "/usr/lib/python3.4/asyncio/futures.py", line 275, in result
        raise self._exception
      File "/usr/local/lib/python3.4/dist-packages/ldapauthenticator/ldapauthenticator.py", line 301, in authenticate
        resolved_username = self.resolve_username(username)
      **File "/usr/local/lib/python3.4/dist-packages/ldapauthenticator/ldapauthenticator.py", line 228, in resolve_username
        is_bound = conn.bind()
      File "/usr/local/lib/python3.4/dist-packages/ldap3/core/connection.py", line 539, in bind
        response = self.post_send_single_response(self.send('bindRequest', request, controls))
      File "/usr/local/lib/python3.4/dist-packages/ldap3/strategy/sync.py", line 124, in post_send_single_response
        responses, result = self.get_response(message_id)
      File "/usr/local/lib/python3.4/dist-packages/ldap3/strategy/base.py", line 331, in get_response
        responses = self._get_response(message_id)
      File "/usr/local/lib/python3.4/dist-packages/ldap3/strategy/sync.py", line 160, in _get_response
        responses = self.receiving()
      File "/usr/local/lib/python3.4/dist-packages/ldap3/strategy/sync.py", line 94, in receiving
        raise communication_exception_factory(LDAPSocketReceiveError, exc)(self.connection.last_error)
    ldap3.core.exceptions.LDAPSocketReceiveError: error receiving data: [Errno 104] Connection reset by peer**
    
[D 2018-08-22 16:07:09.162 JupyterHub base:633] No template for 500
[E 2018-08-22 16:07:09.231 JupyterHub log:114] {
      "Cache-Control": "max-age=0",
      "Origin": "https://my.jupyterhub.edu",
      "Referer": "https://my.jupyterhub.edu/hub/login?next=",
      "Upgrade-Insecure-Requests": "1",
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36",
      "Content-Type": "application/x-www-form-urlencoded",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
      "Accept-Language": "en-US,en;q=0.9,fr;q=0.8",
      "X-Forwarded-For": "132.206.178.43",
      "Connection": "close",
      "Accept-Encoding": "gzip, deflate, br",
      "Host": "my.jupyterhub.edu",
      "Content-Length": "39",
      "Cookie": "_ga=GA1.2.966485689.1530210970; SSESS4d9119e6b043279d0132568957bd2381=Vbadb0KpItO9NrkKkD5tBMkuA9qKkGI2Ni_UeZjAUUQ; _gid=GA1.2.264270059.1534783765",
      "X-Forwarded-Host": "my.jupyterhub.edu",
      "X-Forwarded-Port": "443",
      "X-Forwarded-Proto": "https"
```

**Comment by dhirschfeld** [comment] 2018-08-22 21:57
@tedstrauss - that's a completely different problem so you should open a new issue for it.

The key part of your traceback is:
```
ldap3.core.exceptions.LDAPSocketReceiveError: error receiving data: [Errno 104] Connection reset by peer
```

...which implies you're having trouble connecting to your LDAP server.

Unfortunately I'm not sure what the problem/reason is for that. If you can connect without SSL I'd try that to at least eliminate that as the cause otherwise I can only suggest trying to connect using the underlying [`ldap3`](https://ldap3.readthedocs.io/) library because if you can get that to work it shouldn't be difficult to get `LDAPAuthenticator` working also.

**Comment by JulianTBZ** [comment] 2019-07-24 11:33
Hi, 
I got the same error. 
The following is my configuration. 

> c.JupyterHub.authenticator_class = 'ldapauthenticator.LDAPAuthenticator'
> c.LDAPAuthenticator.server_address= '192.168.1.20'
> c.LDAPAuthenticator.bind_dn_template = [
>     "cn={UserName},OU=Angestellte,OU=Benutzer,OU=KSHP,DC=azure,DC=kshp,DC=ch",
>     "cn={username},OU=Lehrer,OU=Benutzer,OU=KSHP,DC=azure,DC=kshp,DC=ch",
>     "cn={username},OU=Schueler,OU=Benutzer,OU=KSHP,DC=azure,DC=kshp,DC=ch",
> ]
> c.LDAPAuthenticator.lookup_dn = True
> c.LDAPAuthenticator.user_search_base = 'OU=Benutzer,OU=KSHP,DC=azure,DC=kshp,DC=ch'
> c.LDAPAuthenticator.lookup_dn_search_filter = '({login_attr}={login})'
> c.LDAPAuthenticator.user_attribute = 'UserPrincipalName'
> c.LDAPAuthenticator.lookup_dn_search_user = 'CN=adquery,CN=users,DC=azure,DC=kshp,DC=ch'
> c.LDAPAuthenticator.lookup_dn_search_password = 'pai8Namo'
> c.LDAPAuthenticator.lookup_dn_user_dn_attribute = 'cn'
> c.LDAPAuthenticator.user_attribute = 'UserPrincipalName'
> c.LDAPAuthenticator.use_ssl = False
> c.LDAPAuthenticator.escape_userdn = False
> c.LDAPAuthenticator.valid_username_regex = '.+\@.+\..+'

Thanks
