### ISSUE TITLE
v1.3.0 worked, but v1.3.2 gives error "automatic start_tls befored bind not successful"

### ISSUE THREAD

**Issue by evenye** [jupyterhub/ldapauthenticator#187] opened 2020-12-02 12:54 UTC
### Bug description
new version 10.6 ldap can't work with error "automatic start_tls befored bind not successful"
but working well for 0.9.1 version

### How to reproduce

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/usr/local/lib/python3.8/dist-packages/jupyterhub/handlers/login.py", line 144, in post
    user = await self.login_user(data)
  File "/usr/local/lib/python3.8/dist-packages/jupyterhub/handlers/base.py", line 747, in login_user
    authenticated = await self.authenticate(data)
  File "/usr/local/lib/python3.8/dist-packages/jupyterhub/auth.py", line 459, in get_authenticated_user
    authenticated = await maybe_future(self.authenticate(handler, data))
  File "/usr/local/lib/python3.8/dist-packages/ldapauthenticator/ldapauthenticator.py", line 382, in authenticate
    conn = self.get_connection(userdn, password)
  File "/usr/local/lib/python3.8/dist-packages/ldapauthenticator/ldapauthenticator.py", line 314, in get_connection
    conn = ldap3.Connection(
  File "/usr/local/lib/python3.8/dist-packages/ldap3/core/connection.py", line 356, in __init__
    self._do_auto_bind()
  File "/usr/local/lib/python3.8/dist-packages/ldap3/core/connection.py", line 391, in _do_auto_bind
    raise LDAPStartTLSError(error)
ldap3.core.exceptions.LDAPStartTLSError: automatic start_tls befored bind not successful

### Your personal set up

 - OS:
 
 - Version:
 
 - Configuration:

**Comment by manics** [comment] 2021-02-15 22:59
Duplicate of https://github.com/jupyterhub/ldapauthenticator/issues/186

**Closed by manics** 2021-02-15 22:59 UTC
Labels: duplicate
